{"name": "test_001", "status": "failed", "statusDetails": {"message": "AssertionError: GET request returned None\nassert None is not None", "trace": "self = <API_Requests.Tests.test_no_data_found_request.Test_001 object at 0x000001DDFB6E15E0>, setup_teardown = None\n\n    def test_001(self,setup_teardown):\n    \n        \"\"\"\" Test to check GET Request is successful with response and successful status code\"\"\"\n    \n        self.base_url = get_config()['API']['base_url']\n        self.client = RestClient(self.base_url)\n    \n        self.headers = {\n            'Content-Type' : 'application/json'\n        }\n    \n        logging.info(\"*********** executing test_006 ****************\")\n    \n        get_request,status_code = self.client.get_request(end_point=\"unknown/23\", headers=self.headers,response_with_status_code=True,json_data_fmt=True)\n    \n>       assert get_request is not None, \"GET request returned None\"\nE       AssertionError: GET request returned None\nE       assert None is not None\n\nAPI_Requests\\Tests\\test_no_data_found_request.py:27: AssertionError"}, "description": "\" Test to check GET Request is successful with response and successful status code", "attachments": [{"name": "log", "source": "c3ddf879-c937-41d3-8540-e1db64cdb7e6-attachment.txt", "type": "text/plain"}], "start": 1726574190502, "stop": 1726574190966, "uuid": "19a73dd1-11dd-4123-b780-9a086cb1ac09", "historyId": "d7acae85205a2935734d14c95149a29a", "testCaseId": "d7acae85205a2935734d14c95149a29a", "fullName": "API_Requests.Tests.test_no_data_found_request.Test_001#test_001", "labels": [{"name": "parentSuite", "value": "API_Requests.Tests"}, {"name": "suite", "value": "test_no_data_found_request"}, {"name": "subSuite", "value": "Test_001"}, {"name": "host", "value": "NIT2LPT-24-269"}, {"name": "thread", "value": "25572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API_Requests.Tests.test_no_data_found_request"}]}